schema:
  - https://psepamlearning.mybigcommerce.com/graphql
documents:
  - src/main/resources/graphql/**/*.graphql
extensions:
  endpoints:
    default:
      url: https://psepamlearning.mybigcommerce.com/graphql
      headers:
        Authorization: "Bearer token"
      introspect: true
