server:
  port: 8082


spring:
  application:
    name:product-consumer
  kafka:
    template:
      topic-name: bigcommerce_product
    consumer:
      bootstrap-servers: localhost:19092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.bigcommerce.product_consumer.event.ProductCreatedEvent



bigcommerce:
  connection:
    ACCESS_TOKEN: ${ACCESS_TOKEN}
    CLIENT_NAME: ${CLIENT_NAME}
    CLIENT_ID: ${CLIENT_ID}
    CLIENT_SECRET: ${CLIENT_SECRET}
    NAME: Bigcommerce-connection
    API_PATH: ${API_PATH}